### ISSUE TITLE
Add custom environment previews in editor

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/TexturesUnlimited#20]
E.g. a GUI that allows selecting from some pre-rendered environment maps:
* kerbin, daylight
* kerbin, night-time
* LKO, light-side
* LKO, dark-side
* Mun orbit
* Mun landed
* others eventually, maybe...

Would also be good if the lights in the VAB/SPH can be adjusted/dimmed to match the env. map.

## TODO
- [ ] Create Environment maps:
  - [ ] kerbin, daylight (full sun)
  - [ ] kerbin, night-time (no sun, full galaxy visibility)
  - [ ] LKO, light-side (full sun)
  - [ ] LKO, dark-side (no sun, full galaxy visibility)
  - [ ] Mun orbit (full sun)
  - [ ] Mun landed (full sun)
- [ ] Create GUI for in-editor use that allows for switching environment maps.
- [ ] Figure out how to manipulate the in-editor Lights (probably not hard; grab a reference and manipulate away)
- [ ] Create config specifications for the editor lighting for each environment map.
  * VAB and SPH will likely have different configs due to light positions/numbers
  * Might require additional handling for the multiple VAB/SPH levels, as they likely have different Light names/positions/intensities
